ARG emsdk_version=3.1.73
FROM emscripten/emsdk:${emsdk_version}

WORKDIR /

# layer 1 -> rust
COPY Makefile .

ENV PATH="/root/.cargo/bin:${PATH}"
RUN make rust_addons

RUN wget https://raw.githubusercontent.com/pygame-web/python-wasm-sdk/refs/heads/main/emsdk-cc -O$(command -v emcc)

ENTRYPOINT ["make"]